// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXXbY8afgBS0NaEVPHP5MNAOZ_AXQr4q4',
    appId: '1:81208274246:web:60d59d72a4f18b931e0947',
    messagingSenderId: '81208274246',
    projectId: 'yoyo-football-sc',
    authDomain: 'yoyo-football-sc.firebaseapp.com',
    storageBucket: 'yoyo-football-sc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVawIVVU1YkessBUWig_j1JG8IenXSSVI',
    appId: '1:81208274246:android:3cb85b2595eb5b241e0947',
    messagingSenderId: '81208274246',
    projectId: 'yoyo-football-sc',
    storageBucket: 'yoyo-football-sc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTSeBiHIAgD1BibX9PLyfmmrqvk12INs',
    appId: '1:81208274246:ios:0206e64156dcf9801e0947',
    messagingSenderId: '81208274246',
    projectId: 'yoyo-football-sc',
    storageBucket: 'yoyo-football-sc.appspot.com',
    iosClientId: '81208274246-qopap89cehl5keq91pbbc3op955qbjph.apps.googleusercontent.com',
    iosBundleId: 'com.fball.myfootball',
  );
}
